---
- name: test
  gather_facts: False
  hosts: all
  tasks:
  - name: test
    shell:
      /bin/echo 'hello world!'
    register: test_result
  
  - name: output
    debug:
      var: test_result.stdout_lines
